### ISSUE TITLE
Get version from scalafmt.conf?

### ISSUE THREAD

**Issue by raboof** [jrouly/scalafmt-native-action#362]
scala-steward can update scalafmt (https://github.com/raboof/sbt-reproducible-builds/pull/290), but such PRs fail because they don't also update the scalafmt version set in the action parameters.

Perhaps it would be nice if scalafmt-native-action could take the version from .scalafmt.conf ?

**Comment by jrouly** [comment]
Included in [v3](https://github.com/jrouly/scalafmt-native-action/releases/tag/v3).
