### ISSUE TITLE
new release (v4 or otherwise)

### ISSUE THREAD

**Issue by pjfanning** [jrouly/scalafmt-native-action#379]
@jrouly would it be possible to get a new release?

The change that I need is https://github.com/jrouly/scalafmt-native-action/pull/372

GitHub CI is soon going to stop allowing Node 16.

**Comment by jrouly** [comment]
Yep, will release as v4.

**Comment by jrouly** [comment]
https://github.com/jrouly/scalafmt-native-action/releases/tag/v4
